import 'bulma/css/bulma.css'
import 'font-awesome/css/font-awesome.css'
import 'toastr/build/toastr.min.css'
import 'flatpickr/dist/flatpickr.min.css'
import 'lightbox2/dist/css/lightbox.css'
import  './app.css'
import 'blockUI'
